### ISSUE TITLE
Dynect calls not stable

### ISSUE THREAD

**Issue by rameshraithatha** [adamhjk/dynect_rest#38]
Hi,
We're using 0.4.3 of the dynect-rest gem since Jan this year and so far its worked really well. However in the last week or so we've had several of our enable /disable calls for gslb entries  that have failed intermittently. Has anyone else here faced the same ? The logs that lead to this are as follows
["/usr/local/share/gems1.9/gems/dynect_rest-0.4.3/lib/dynect_rest.rb:209:in `parse_response'", "/usr/local/share/gems1.9/gems/dynect_rest-0.4.3/lib/dynect_rest.rb:197:in `api_request'", "/usr/local/share/gems1.9/gems/dynect_rest-0.4.3/lib/dynect_rest.rb:144:in `get'", "/usr/local/share/gems1.9/gems/dynect_rest-0.4.3/lib/dynect_rest.rb:193:in `rescue in api_request'", "/usr/local/share/gems1.9/gems/dynect_rest-0.4.3/lib/dynect_rest.rb:185:in `api_request'", "/usr/local/share/gems1.9/gems/dynect_rest-0.4.3/lib/dynect_rest.rb:180:in `put'", 
"/opt/dyn.rb:206:in `update_dynect_entry'",]

We're guessing its because of Dynect and not dynect_rest api. Does anyone else have the same issue?

**Comment by ranjib** [comment]
@rameshraithatha sorry for getting back so late. Im  triaging the issues now. Does this problem still exist? @evan2645 comments?

**Comment by evan2645** [comment]
@rameshraithatha we have seen similar. We've also assumed that it's due to Dynect funniness, especially since the behavior was introduced without any upgrades or other changes.

I suspect it's hitting one of the raised exceptions in parse_response... possibly due to jobs backing up in the Dynect infra. Is there any more information in your logs besides the stacktrace?

We have not seen the problem for a couple months now.

**Comment by rameshraithatha** [comment]
@ranjib @evan2645 Thanks for looking into this. Seems like it was due to Dynect and its working perfectly fine now.

I'll close the ticket, thanks.
